version: 0.1

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - echo Build started on `date`
      - gradlew bootJar
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'